version: '3'

services:
  web:
    image: 'nginx:alpine'
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      net:
        aliases:
          - boletin-cyt.dev

  php:
    image: php:7.2.1-fpm-alpine3.7
    volumes:
      - ./:/var/www/html
    networks:
      - net

networks:
  net:
    driver: bridge