version: '3'

services:
  mariadb:
    image: 'mariadb:10.2.11'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=boletincyt 
      - MYSQL_USER=boletincyt 
      - MYSQL_PASSWORD=boletincyt 
      - MYSQL_ROOT_PASSWORD=boletincyt

networks:
  default: