version: '3'

services:
  app:
    image: 'sportesi/boletin-cyt:latest'
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - net
      
networks:
  net:
    driver: bridge