version: '3'

services:

  web:
    image: sportesi/boletin-cyt:latest
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html

  mariadb:
    image: 'mariadb:10.2.11'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=boletincyt 
      - MYSQL_USER=boletincyt 
      - MYSQL_PASSWORD=boletincyt 
      - MYSQL_ROOT_PASSWORD=boletincyt
    volumes:
      - boletin_db:/var/lib/mysql

  mailhog:
    image: 'mailhog/mailhog'
    ports:
     - 8025:8025
     - 1025:1025

networks:
  default:

volumes:
  boletin_db: