version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: sportesi/boletin-cyt:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Composer install
          command: composer install
      - run:
          name: Run tests
          command: ./vendor/bin/phpunit

workflows:
  welcome:
    jobs:
      - build