version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: sportesi/boletin-cyt:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: mariadb:10.2.11
        environment:
          - MYSQL_DATABASE=boletincyt
          - MYSQL_USER=boletincyt
          - MYSQL_PASSWORD=boletincyt
          - MYSQL_ROOT_PASSWORD=boletincyt
    steps:
      - checkout
      - run:
          name: Composer install
          command: composer install
      - run:
          name: Copy env example
          command: cp .env.example .env
      - run:
          name: Give storage permissions
          command: chmod -R 777 storage
      - run:
          name: Run tests
          command: ./vendor/bin/phpunit

workflows:
  welcome:
    jobs:
      - build